apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-deployment
  labels:
  {{- include "labels" . | nindent 4}}
spec:
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      {{- include "labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ $.Release.Name }}-container
          image: {{ $.Values.deployment.container.image }}
          ports:
            - containerPort: {{ $.Values.deployment.container.port }}