apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-ingress
  labels:
  {{- include "labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ $.Values.ingress.host }}
      http:
        paths:
          - path: {{ $.Values.ingress.path }}
            pathType: {{ $.Values.ingress.pathType }}
            backend:
              serviceName: {{ $.Release.Name }}-service
              servicePort: {{ $.Values.service.ports.port }}